package middleware

import (
	"log/slog"
	"net/http"

	chimw "github.com/go-chi/chi/v5/middleware"

	"github.com/timurdianradhasejati/telemed_hub/pkg/logger"
)

// TraceIDMiddleware reads the request ID generated by chi's RequestID
// middleware, propagates it into a custom context key (so pkg/logger can
// extract it), sets the X-Request-Id response header, and creates an
// enriched child *slog.Logger that includes "trace_id" on every log entry.
//
// Place this middleware AFTER chi/middleware.RequestID in the chain.
func TraceIDMiddleware(log *slog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			// Read the request ID that chi already generated.
			reqID := chimw.GetReqID(r.Context())

			// Store trace ID in our own context key.
			ctx := logger.CtxWithTraceID(r.Context(), reqID)

			// Create a child logger enriched with the trace ID.
			enrichedLog := log.With("trace_id", reqID)
			ctx = logger.CtxWithLogger(ctx, enrichedLog)

			// Propagate trace ID to the response header so callers can correlate.
			w.Header().Set("X-Request-Id", reqID)

			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
